apiVersion: v1
kind: ConfigMap
metadata:
  name: christine-agent-config
  namespace: christine-agent
data:
  armory-agent.yaml: |
    clouddriver:
      grpc: a6f6a04f266094a5a957bda1b0bab076-1695378165.us-east-2.elb.amazonaws.com:9091
      insecure: true
    kubernetes:
      accounts:
        - kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret
          name: christine-agent-sa
          insecure:
          context:
          oAuthScopes:
          serviceAccount: true
          serviceAccountName: christine-agent-sa
          namespaces: []
          omitNamespaces: []
          onlyNamespacedResources:
          kinds: []
          omitKinds: []
          customResourceDefinitions: [{kind:}]
          metrics:
          permissions: []
          maxResumableResourceAgeMs:
          onlySpinnakerManaged:
          noProxy: