#-----------------------------------------------------------------------------------------------------------------
# Example configuration for adding the Kubernetes Agent plugin to clouddriver
#
# Documentation: https://docs.armory.io/docs/armory-agent/armory-agent-quick/
#-----------------------------------------------------------------------------------------------------------------
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:


    profiles:
      clouddriver:
        kubernetes:
          enabled: true    # This is not needed if spinnaker already has kubernetes V2 accounts enabled by other files

        sql:
          enabled: true    # kubesvc depends on clouddriver using SQL. See patch-sql-clouddriver for full configuration
        redis:
          enabled: true    # kubesvc depends on redis for internal pub/sub communication

        kubesvc:
          cluster: redis

        spinnaker:
          extensibility:
            pluginsRootPath: /opt/clouddriver/lib/plugins
            plugins:
              Armory.Kubesvc:
                enabled: true
                extensions:
                  armory.kubesvc:
                    enabled: true
              Armory.PreConfiguredJobPlugin.RunScript:
                enabled: true
                config:
                  account: kubernetes
                  credentials: kubernetes
                  artifactServiceUrl: http://localhost:7002
                  gitArtifactAccount: AT_GitRepo
                # Optional: override default init container image 
                  initContainerImage: myrepo/fetch-artifact:latest
        aws:
          features:
            lambda:
              enabled: true
          accounts:
          - name: christine-aws                        # NOTE: profiles.clouddriver.aws.accounts is merged with config.provider.aws.accounts by INDEX not accounts.name
            lambdaEnabled: true
            accountId: "810711266228"            # (Required). Your AWS account ID to manage. See the AWS IAM User Guide for more information.
            assumeRole: role/aws-spin-support-managedrole
      gate:
        # 2022-09-27 added below 4607 autodesk 
        # https://spinnaker.io/docs/setup/productionize/caching/externalize-redis/
        redis:
            configuration:
                secure:
                      true
        spinnaker:
          extensibility:
              deck-proxy:
                enabled: true
                plugins:
                  Aws.LambdaDeploymentPlugin:
                    enabled: true
                    version: 1.0.11
              repositories:
                awsLambdaDeploymentPluginRepo:
                  url: https://raw.githubusercontent.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/master/plugins.json
      orca:
        spinnaker:
          extensibility:
            plugins:
              Aws.LambdaDeploymentPlugin:
                enabled: true
                version: 1.0.11
              extensions:
                lambdaDeploymentStage:
                  config:
                    defaultMaxWaitTime: 20    # default 20
            repositories:
              awsLambdaDeploymentPluginRepo:
                id: awsLambdaDeploymentPluginRepo
                url: https://raw.githubusercontent.com/spinnaker-plugins/aws-lambda-deployment-plugin-spinnaker/master/plugins.json
  kustomize:
    clouddriver:
      service:
        patchesStrategicMerge:
          - |
            spec:
              ports:
                - name: http
                  port: 7002
                - name: grpc
                  port: 9091
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  initContainers:
                  - name: kubesvc-plugin
                    image: docker.io/armory/kubesvc-plugin:0.10.38  # See https://docs.armory.io/docs/armory-agent/armory-agent-quick/ for available versions
                    volumeMounts:
                      - mountPath: /opt/plugin/target
                        name: kubesvc-plugin-vol
                  containers:
                  - name: clouddriver
                    volumeMounts:
                      - mountPath: /opt/clouddriver/lib/plugins
                        name: kubesvc-plugin-vol
                  volumes:
                  - name: kubesvc-plugin-vol
                    emptyDir: {}
