apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spin-role
rules:
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: spin-agent
  name: spin-sa
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spin-role-binding
subjects:
  - kind: ServiceAccount
    name: spin-sa
    namespace: christine-zhao
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spin-role