apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
  # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      deploymentEnvironment:
        customSizing:
          spin-deck:
            replicas: 1
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          spin-echo:
            replicas: 1
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          echo:
            limits:
              cpu: 250m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 1Gi
          spin-gate:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-clouddriver:
            replicas: 1
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          clouddriver:
            limits:
              cpu: 1000m
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 2Gi
          spin-orca:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-front50:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-igor:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-rosco:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-redis:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi
          spin-terraformer:
            limits:
              cpu: 1000m
              memory: 4Gi
            replicas: 1
            requests:
              cpu: 500m
              memory: 2Gi