apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
  # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      version: 2.28.0  # the version of Spinnaker to be deployed
      artifacts:
        # helm:
        #   enabled: true
        #   accounts:
        #     name: jfrog
        #     repository: https://charts.jfrog.io
        gitrepo:
          enabled: true
          accounts:
            - name: AT_GitRepo
              username: ChristineZhaoArmory                # Git username.
              #token: encrypted:k8s!n:spin-secrets!k:github-token 
              token: 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  #2022-08-18 change to text token
        github:
          enabled: true
          accounts:
            - name: AT_Github
              username: ChristineZhaoArmory                # Git username.
              # token: encrypted:k8s!n:spin-secrets!k:github-token
              token: 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  #2022-08-18 change to text token
        # christine- 2022-06-13 have problem. Need check later
        s3:
          enabled: true
          accounts:
          - name: AT_S3
            region: us-east-2
          # - name: us_east_1_S3
          #   region: us-east-1
        #     awsAccessKeyId: ASIA3ZQRIGO2LOT4OUGH
        #     awsSecretAccessKey: encrypted:k8s!n:spin-secrets!k:aws-secret-key
      persistentStorage:
        persistentStoreType: s3
        s3:
          bucket: christine-zhao-s3
          rootFolder: front50
          region: us-east-2
      security:
        apiSecurity:
          overrideBaseUrl: https://christine-spin-gate.tse-armory.io  # Specify your DNS name for Gate with https scheme
        uiSecurity:
          overrideBaseUrl: https://christine-spin-deck.tse-armory.io       # Specify your DNS name for Deck with https scheme
        authn:
          oauth2:
            enabled: true
            client:
              clientId: f074440fd5b990f4aca0
              clientSecret: encrypted:s3!r:us-east-2!b:christine-zhao-s3!f:secret/spinnaker-secrets.yml!k:github.token
              userAuthorizationUri: https://github.com/login/oauth/authorize
              scope: user:org,user:email
              preEstablishedRedirectUri: https://christine-spin-gate.tse-armory.io/login
            provider: GITHUB
      providers:
        kubernetes:
          enabled: true
          accounts:
          - name: christine-sa
            requiredGroupMembership: []
            providerVersion: V2
            permissions: {}
            dockerRegistries: []
            configureImagePullSecrets: true
            cacheThreads: 1
            namespaces: []
            omitNamespaces: []
            kinds: []
            omitKinds: []
            customResources: []
            cachingPolicies: []
            oAuthScopes: []
            onlySpinnakerManaged: true
            kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret
          primaryAccount: christine-sa
        # BEGIN 2022-08-15 close for removing exceptions
        aws:
          accounts:
          - accountId: '810711266228'
            providerVersion: V1
            name: christine-aws
            regions:
            - name: us-east-2
            - name: us-east-1
            - name: us-west-1
            - name: us-west-2
            assumeRole: role/aws-spin-support-managedrole
            requiredGroupMembership: []
          bakeryDefaults:
            baseImages:
            - baseImage:
                detailedDescription: debian11
                id: debian
                shortDescription: v11
                packageType: deb
                templateFile: aws-ebs.json
              virtualizationSettings:
              - instanceType: t2.micro
                region: us-west-2
                # sourceAmi: ami-0d70546e43a941d70 #ubuntu
                sourceAmi: ami-071e6cafc48327ca2
                spotPrice: “0”
                spotPriceAutoProduct: Linux/UNIX (Amazon VPC)
                sshUserName: admin
                virtualizationType: hvm
          defaultKeyPairTemplate: ‘{{“{{“}}name{{“}}“}}-keypair’
          defaultRegions:
          - name: us-east-1
          - name: us-east-2
          - name: us-west-1
          - name: us-west-2
          defaults:
            iamRole: BaseIAMRole
          enabled: true
          features:
            cloudFormation:
              enabled: true
          primaryAccount: christine-aws
        # END 2022-08-15 close for removing exceptions
        # ecs:
        #   enabled: true
        #   accounts:
        #   - name: aws-dev-ecs
        #     requiredGroupMembership: []
        #     providerVersion: V1
        #     permissions: {}
        #     awsAccount: aws-dev                   # Must be one of the configured AWS accounts
        #   primaryAccount: aws-dev-ecs             # Must be one of the configured AWS ECS accounts
      deploymentEnvironment:
        customSizing:
          echo:
            limits:
            #  cpu: 250m
            # memory: 512Mi
            # requests:
            #   cpu: 100m
            #   memory: 128Mi
          spin-clouddriver:
            sreplicas: 2
            limits:
              # cpu: 600m
            #  memory: 3Gi
            # requests:
            #   cpu: 250m
            #   memory: 512Mi
          clouddriver:
            limits:
              # cpu: 801m
            #  memory: 2Gi
            # requests:
            #   cpu: 250m
            #   memory: 512Mi
      armory:
        terraform:
          enabled: true

        # christine- 2022-05-31 below is enable diagnostics and logging
        # https://docs.armory.io/armory-enterprise/armory-admin/observe/diagnostics-configure/
        # diagnostics:
        #   enabled:    true
        #   uuid:       # Enter uniquely Generated UUID
        #   logging:
        #     enabled:    # true/false to enable
        #     endpoint:   # Enter Endpoint, e.g. https://debug.armory.io/v1/logs
        # christine- 2022-05-31 above is enable diagnostics and logging