apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sql-debug
  namespace: christine-zhao
  labels:
    app: k8s-sql-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-sql-debug
  template:
    metadata:
      labels:
        app: k8s-sql-debug
    spec:
      containers:
      - name: k8s-sql-debug
        image: mysql:latest
        imagePullPolicy: Always
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password