apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- SpinnakerService.yml
- expose/ingress-nginx.yml # 2023-01-06 Spinnaker ingress definition

#--------------------THIS ARE TOOLS. CANNOT BE REMVOED--------------------
#- k8s-sql-debug.yml
#- jenkins.yml # 2022-08-22 added
#- servicemonitor.yml # 2022-11-02 Prometheus ServiceMonitor
#- infrastructure/debugging-tools.yml # (Optional). A pod with some tools for troubleshooting spinnaker (curl, kubectl, vault, etc.)
#--------------------THIS ARE TOOLS. CANNOT BE REMVOED--------------------

# #- clouddriver-logback.yml # 2022-08-23 add logback
#- logback-config.yml # 2022-08-24 add generic logback
                      # 2022-08-27 closed because too much logs

- armory-agent/service.clouddriver.yml
- armory-agent/agent.configmap.yml
- armory-agent/agent.deployment.yml

#- spin-agent-clouddriver.yml  # agent step 2: This create spin-clouddriver-gRPC service to acconnect clouddriver plugin
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- armory-agent/role-binding.yml # agent step 3: This create serviceaccount christine-agent-na in christine-agent namespace
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- armory-agent/configmap.yml # This is defined in armory-agent/kustomization.yaml
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- monitor_from_austin.yml

#- infrastructure/opa.yml

# Apply the patches top down order
patchesStrategicMerge:
- config-patch.yml
- config-customsizing-limits.yml # 2022-11-14 move this part out from config-patch.yml
#- version.yml    # 2022-12-13 test version 2.28.2-rc2 30889 
                  # 2022-12-15 2.24.2 for SUPPORT-4730
                  # 2022-12-22 test 2.26.4 for SUPPORT-4871
- files-patch.yml
- service-settings-patch.yml
- service-patch.yml  # 2022-10-19 temporary remove to test pere snap badpipine
- profiles-patch.yml
# - profile-orca.yml  # 2022-11-16 disable to test 2.28.1-rc3
- profile-clouddriver.yml
#- notifications/patch-email.yml

- armory-agent/plugin.clouddriver.yml # agent step 1: This create clouddriver plugin
                                       # 2023-01-03 test 2.27
#- patch-logging.yml    # 2022-08-23 add logback 
                        # 2022-08-24 mergered into profile-clouddriver an service-settings-patch.yml

#- plugin-observability.yml #2022-11-04 prometheus
#- patch-diagnostics.yml # 2022-08-23 added

#- canary/prometheus.yml # 2022-10-29 added
#- canary/cloudwatch.yml # 2022-12-12 added

#- patch-dockerhub.yml

#
# - patch-external-authz.yml # 2022-11-22 This cause Access denied to account christine-sa. 
# - security/patch-saml.yml  # 2022-11-22 added 2022-12-15 closed
#

#
#- security/patch-github.yml # 2022-12-12
#

#- security/patch-fiat-create-app-roles.yml # 2022-11-20 added, not working
#- security/patch-file-authz.yml            # 2022-11-20 added, not working

# Armory features
#- patch-dinghy.yml         # Store spinnaker pipelines as code under source control

#- patch-terraformer.yml    # Store infrastructure as code under source control

#- patch-policy-and-agent-plugins.yml # Added 2022-06-13 for policy engine
                                       # 2022-08-17 resume agent later
- patch-policy-engine-plugin.yml # 2022-08-11 Change to this version for testing
                                 # 2022-08-25 temporary close to test others
                                 # 2023-01-06

#- patch-startupprobes.yml # 2022-11-09 pass clouddriver

- expose/patch-ingress.yml # Read ingress definition to configure spinnaker public facing urls.


# configMapGenerator:  # Added 2022-06-13 for policy engine
#   # ConfigMap holding OPA policy definitions to use by Armory's policy engine. Required by patch-policyengine.yml
#   - name: spin-policies
#     files:
#     - policies/pipelinepersistance.rego
#     - policies/manual-judgement.rego