apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- SpinnakerService.yml
- k8s-sql-debug.yml
- jenkins.yml # 2022-08-22 added
- servicemonitor.yml
- infrastructure/debugging-tools.yml # (Optional). A pod with some tools for troubleshooting spinnaker (curl, kubectl, vault, etc.)

# #- clouddriver-logback.yml # 2022-08-23 add logback
- logback-config.yml # 2022-08-24 add generic logback

- armory-agent/service.clouddriver.yml

- armory-agent/agent.configmap.yml
- armory-agent/agent.deployment.yml

#- spin-agent-clouddriver.yml  # agent step 2: This create spin-clouddriver-gRPC service to acconnect clouddriver plugin
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- armory-agent/role-binding.yml # agent step 3: This create serviceaccount christine-agent-na in christine-agent namespace
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- armory-agent/configmap.yml # This is defined in armory-agent/kustomization.yaml
# move spin-agent-clouddriver to armory-agent/kustomization.yaml

#- monitor_from_austin.yml

#- infrastructure/opa.yml

# Apply the patches top down order
patchesStrategicMerge:
- config-patch.yml
- files-patch.yml
- service-settings-patch.yml
- service-patch.yml
- profiles-patch.yml
- profile-clouddriver.yml
- notifications/patch-email.yml

#- armory-agent/plugin.clouddriver.yml # agent step 1: This create clouddriver plugin
                                       # 2022-08-24 resume agent later
#- patch-logging.yml    # 2022-08-23 add logback 
                        # 2022-08-24 mergered into profile-clouddriver an service-settings-patch.yml

- plugin-observability.yml #2022-08-22 prometheus
- patch-diagnostics.yml # 2022-08-23 added

#- patch-dockerhub.yml

#- patch-external-authz.yml # 2022-08-16 This cause Access denied to account christine-sa. 
                            # need to Check later

# Armory features
- patch-dinghy.yml         # Store spinnaker pipelines as code under source control
- patch-terraformer.yml    # Store infrastructure as code under source control

#- patch-policy-and-agent-plugins.yml # Added 2022-06-13 for policy engine
                                       # 2022-08-17 resume agent later
- patch-policy-engine-plugin.yml # 2022-08-11 Change to this version for testing
                                 # 2022-08-24 temporary close to test others

- patch-startupprobes.yml

# configMapGenerator:  # Added 2022-06-13 for policy engine
#   # ConfigMap holding OPA policy definitions to use by Armory's policy engine. Required by patch-policyengine.yml
#   - name: spin-policies
#     files:
#     - policies/pipelinepersistance.rego
#     - policies/manual-judgement.rego