resources:
- SpinnakerService.yml

# Apply the patches top down order
patchesStrategicMerge:
- config-patch.yml
- profiles-patch.yml
- files-patch.yml
- service-settings-patch.yml
- service-patch.yml

# Armory features
#- patch-dinghy.yml         # Store spinnaker pipelines as code under source control
#- patch-terraformer.yml    # Store infrastructure as code under source control