apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.profiles - This section contains the YAML of each service's profile
    profiles:
      spinnaker:
        spinnaker:  # This second `spinnaker` is required
          extensibility:
            plugins:
              Armory.EvaluateArtifactsPlugin:
                enabled: true
                version: 0.1.1 # Replace with the version you want to use. For example, use 0.1.0.
            repositories:
              evaluateArtifacts:
                url: https://raw.githubusercontent.com/armory-plugins/evaluate-artifacts-releases/master/repositories.json
                #url: https://raw.githubusercontent.com/armory-plugins/evaluate-artifacts-releases/master/plugins.json
      clouddriver: # is the contents of ~/.hal/default/profiles/clouddriver.yml
        serviceLimits:
          defaults:
          rateLimit: 10.0
        #   implementationLimits:
        #     ## Examples - default rate limit is 10, reducing these can reduce AWS API calls preventing throttling but it's FAR better to get a support ticket in...  and increase the API limits.
        #     AmazonAutoScaling:
        #       defaults:
        #         rateLimit: 3.0
        #     AmazonElasticLoadBalancing:
        #       defaults:
        #         rateLimit: 10.0   # default max req/second
        #   cloudProviderOverrides:
        #     aws:
        #       rateLimit: 10.0
      # deck has a special key "settings-local.js" for the contents of settings-local.js
      deck:
        # settings-local.js - contents of ~/.hal/default/profiles/settings-local.js
        # Use the | YAML symbol to indicate a block-style multiline string
        settings-local.js: |
          window.spinnakerSettings = window.spinnakerSettings || {};
          window.spinnakerSettings.notifications = window.spinnakerSettings.notifications || {};
          window.spinnakerSettings.notifications.email = window.spinnakerSettings.notifications.email || {};
          window.spinnakerSettings.notifications.email.enabled = true;
          window.spinnakerSettings.feature.kustomizeEnabled = true;
          window.spinnakerSettings.feature.artifactsRewrite = true;
          window.spinnakerSettings.feature.terraform = true;
          window.spinnakerSettings.feature.functions = true;
          window.spinnakerSettings.pubsubProviders = ['google', 'amazon'];
          window.spinnakerSettings.providers.aws.serverGroups = {
              enableLaunchTemplates: true,
              enableIPv6: true,
              enableIMDSv2: true,
              enableCpuCredits: true,
          };
          window.spinnakerSettings.feature.quietPeriod = true;
          window.spinnakerSettings.authEnabled = true;
          window.spinnakerSettings.feature.managedServiceAccounts = true;
      echo:   # is the contents of ~/.hal/default/profiles/echo.yml
        orca.enabled: true # 2022-09-15 https://support.armory.io/support?sys_kb_id=08b0efa41ba1f01013d4fe6fdc4bcb58&id=kb_article_view&sysparm_rank=33&sysparm_tsqueryId=0e3f1fbf1b751d5004ef3377cc4bcb79
        # pubsub:
        #   enabled: true
        #   amazon:
        #     enabled: true
        #     subscriptions:
        #     - name: christine-pubsub-2n
        #       #topicARN: arn:aws:sns:us-east-2:810711266228:christine-pubsub-topic-2         # (Required).
        #       #queueARN: arn:aws:sqs:us-east-2:810711266228:christine-pubsub-test-queue-2    # (Required).
        #       topicARN: arn:aws:sns:us-east-2:810711266228:sunny-test-topic                                                   # (Required).
        #       queueARN: arn:aws:sqs:us-east-2:810711266228:sunny-test-queue
        #       messageFormat: NONE
        #     # - name: christine-pubsub                                                      # (Required).
        #     #   topicARN: arn:aws:sns:us-east-2:810711266228:spin-alc-pubsub-topic         # (Required).
        #     #   queueARN: arn:aws:sqs:us-east-2:810711266228:spin-alc-pubsub-test-queue    # (Required).
        #     #   messageFormat: S3
        # #logging.level.com.netflix.spinnaker.echo: DEBUG
        # logging.level.com.netflix.spinnaker.echo.pubsub.aws: DEBUG
        # logging.level.com.netflix.spinnaker.echo.config.AmazonPubsubProperties: DEBUG
      fiat: {}    # is the contents of ~/.hal/default/profiles/fiat.yml
      front50: {} # is the contents of ~/.hal/default/profiles/front50.yml
      gate: #{}      # is the contents of ~/.hal/default/profiles/gate.yml
        # 2022-09-27 added below 4607 autodesk 
        # https://spinnaker.io/docs/setup/productionize/caching/externalize-redis/
        # redis:
        #   configuration:
        #     secure: true
        #
        #2022-09-26 below for EvaluateArtifactsPlugin
        spinnaker:
          extensibility:
            deck-proxy:
              enabled: true
              plugins:
                Armory.EvaluateArtifactsPlugin:
                  enabled: true
                  version: 0.1.1 # Replace with the version you want to use. For example, use 0.1.0.
      igor: {}    # is the contents of ~/.hal/default/profiles/igor.yml
      kayenta: {} # is the contents of ~/.hal/default/profiles/kayenta.yml
      rosco:      # is the contents of ~/.hal/default/profiles/rosco.yml
        logging:
          level:
            com.netflix.spinnaker.rosco: DEBUG
