apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.profiles - This section contains the YAML of each service's profile
    profiles:
      clouddriver: # is the contents of ~/.hal/default/profiles/clouddriver.yml
        aws:
          accounts:
            - accountId: '810711266228'
              assumeRole: role/aws-spin-support-access
              lambdaEnabled: true
              name: christine-aws
          features:
            lambda:
              enabled: true
            launch-templates:
              allowed-accounts: support-dev
              allowed-applications:
                all-applications:
                  enabled: true
              enabled: true
        serviceLimits:
          defaults:
          rateLimit: 10.0
          implementationLimits:
            ## Examples - default rate limit is 10, reducing these can reduce AWS API calls preventing throttling but it's FAR better to get a support ticket in...  and increase the API limits.
            AmazonAutoScaling:
              defaults:
                rateLimit: 3.0
            AmazonElasticLoadBalancing:
              defaults:
                rateLimit: 10.0   # default max req/second
          cloudProviderOverrides:
            aws:
              rateLimit: 10.0
        # logging:
        #   level:
        #     com.netflix.spinnaker.clouddriver: DEBUG
        #   config: /opt/spinnaker/config/logging/logback-config.xml #2022-08-27 closed because too much logs
        sql:
          enabled: true
          read-only: false 
          taskRepository:
            enabled: true
          cache:
            enabled: true
            readBatchSize: 500
            writeBatchSize: 300
          scheduler:
            enabled: true
          unknown-agent-cleanup-agent:
            enabled: false
          connectionPools:
            default:
              default: true
              jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
              user: clouddriver_service
              password: armory
            tasks:
              user: clouddriver_service
              jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
              password: armory
          migration:
            user: clouddriver_migrate
            jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
            password: armory
        redis:
          enabled: true # Christine- 2022-05-31 change from false to true
          cache:
            enabled: false
          scheduler:
            enabled: false
          taskRepository:
            enabled: false