apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.profiles - This section contains the YAML of each service's profile
    profiles:
      clouddriver: # is the contents of ~/.hal/default/profiles/clouddriver.yml
        artifacts:   # https://spinnaker.io/docs/setup/other_config/artifacts/gitrepo/
          gitrepo:
            clone-retention-minutes: -1 #retain forever.
            clone-retention-max-bytes: 104857600
        aws:
          accounts:
            - accountId: '810711266228'
              #assumeRole: role/aws-spin-support-access
              assumeRole: role/aws-spin-support-managedrole
              lambdaEnabled: true
              name: christine-aws
          features:
            lambda:
              enabled: true
            launch-templates:
              allowed-accounts: support-dev
              allowed-applications:
                all-applications:
                  enabled: true
              enabled: true
        serviceLimits:
          defaults:
          rateLimit: 10.0
          implementationLimits:
            ## Examples - default rate limit is 10, reducing these can reduce AWS API calls preventing throttling but it's FAR better to get a support ticket in...  and increase the API limits.
            AmazonAutoScaling:
              defaults:
                rateLimit: 10.0   # 2022-11-03 change to 10.0 from 3.0
            AmazonElasticLoadBalancing:
              defaults:
                rateLimit: 10.0   # default max req/second
          cloudProviderOverrides:
            aws:
              rateLimit: 10.0
        logging:
          level:
            com.netflix.spinnaker.clouddriver: DEBUG
        #   config: /opt/spinnaker/config/logging/logback-config.xml #2022-08-27 closed because too much logs
        sql:
          enabled: true
          read-only: false 
          taskRepository:
            enabled: true
          cache:
            enabled: true
            readBatchSize: 500
            writeBatchSize: 300
          scheduler:
            enabled: true
          unknown-agent-cleanup-agent:
            enabled: true # 2022-09-07 Enable the cleanup agent - clean up spinnaker by deleting these decom'd clusters
          connectionPools:
            default:
              default: true
              jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
              user: clouddriver_service
              password: armory # Christine 2022-09-29
            tasks:
              user: clouddriver_service
              jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
              password: armory # Christine 2022-09-29
          migration:
            user: clouddriver_migrate
            jdbcUrl: jdbc:mysql://christine-aurora-mysql.cluster-cddfke67dweh.us-east-2.rds.amazonaws.com:3306/clouddriver
            password: armory # Christine 2022-09-29
        redis:
          enabled: false # Christine 2023-01-03 using kubesvc.cluster: kubernetes, you should not use redis 
          cache:
            enabled: true
          scheduler:
            enabled: true
          taskRepository:
            enabled: true