apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spin
    app.kubernetes.io/name: armory-agent
    app.kubernetes.io/part-of: spinnaker
    cluster: spin-armory-agent
  name: spin-armory-agent
  namespace: christine-spin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spin
      cluster: spin-armory-agent
  template:
    metadata:
      labels:
        app: spin
        app.kubernetes.io/name: armory-agent
        app.kubernetes.io/part-of: spinnaker
        cluster: spin-armory-agent
    spec:
      # logging:
      #   level: debug
      serviceAccount: spin-sa # 2023-01-06 christine-spin-sa
      containers:
        - image: armory/agent-k8s:1.0.33 # must be compatible with your Armory Enterprise version
                                         # 2022-10-06 Armory Enterprise version 2.28
                                         # https://v2-27.docs.armory.io/armory-enterprise/release-notes/rn-armory-agent/agent-plugin/
          imagePullPolicy: IfNotPresent
          # env:
          # - name: LOG_LEVEL
          #   value: trace
          name: armory-agent
          ports:
          - name: health
            containerPort: 8082
            protocol: TCP
          - name: metrics
            containerPort: 8008
            protocol: TCP
          livenessProbe:
            httpGet:
              port: health
              path: /health
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/armory/config
              name: volume-armory-agent-config
            - mountPath: /kubeconfigfiles
              name: volume-armory-agent-kubeconfigs
      restartPolicy: Always
      volumes:
      - name: volume-armory-agent-config
        configMap:
          name: armory-agent-config
      - name: volume-armory-agent-kubeconfigs
        secret:
          defaultMode: 420
          secretName: spin-secrets-remote # 2023-01-06 kubeconfigs-secret
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: armory-agent-metrics
#   labels:
#     app: armory-agent
#     cluster: armory-agent
# spec:
#   ports:
#   - name: metrics
#     port: 8008
#     targetPort: metrics
#     protocol: TCP
#   selector:
#     app: armory-agent
#     cluster: armory-agent