apiVersion: v1
kind: ConfigMap
metadata:
  name: armory-agent-config
  namespace: spin-agent
data:
  armory-agent.yaml: |
    clouddriver:
      grpc: spin-clouddriver-grpc:9091
      insecure: true
    kubernetes:
      accounts:
      - name: christine-agent
        kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret
        #kubeconfigFile: encryptedFile:vault!e:secret!p:spinnaker/kubernetes!k:config
        # insecure:
        # context:
        # oAuthScopes:
        # serviceAccount: true
        # serviceAccountName: christine-spin-sa
        # namespaces: [spin-agent,christine-agent]
        # omitNamespaces: []
        # onlyNamespacedResources:
        kinds: []
        omitKinds: []
        # customResourceDefinitions: [{kind:}]
        metrics: false
        # permissions: []
        # maxResumableResourceAgeMs:
        # onlySpinnakerManaged:
        # noProxy:
