apiVersion: v1
kind: ConfigMap
metadata:
  name: armory-agent-config
  namespace: christine-spin
data:
  armory-agent.yaml: |
    clouddriver:
      grpc: spin-clouddriver-grpc.christine-zhao.svc.cluster.local:9091
      insecure: true
    logging:
      level: debug
    kubernetes:
      accounts:
      - name: christine-spin-sa
        kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret
        #kubeconfigFile: encryptedFile:vault!e:secret!p:spinnaker/kubernetes!k:config
        # insecure:
        # context:
        # oAuthScopes:
        # serviceAccount: true
        serviceAccountName: christine-spin-sa
        namespaces: [christine-rna,christine-spin,christine-zhao]
        # omitNamespaces: []
        # onlyNamespacedResources:
        kinds: []
        omitKinds: []
        # customResourceDefinitions: [{kind:}]
        metrics: false
        # permissions: []
        # maxResumableResourceAgeMs:
        # onlySpinnakerManaged:
        # noProxy:
