apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      clouddriver:
        logging.level.io.armory.kubesvc.services.ops.cluster.kubernetes: DEBUG # 2022-11-03 by Adan
        spinnaker:
          extensibility:
            pluginsRootPath: /opt/clouddriver/lib/plugins
            plugins:
              Armory.Kubesvc:
                enabled: true
        # Plugin config
        kubesvc:
          cluster: kubernetes
        # logging:
        #   level:
        #     io.armory.kubesvc: DEBUG
          # cache:
          #   operationWaitMs: 60000
          # runtime:
          #   defaults:
          #     onlySpinnakerManaged: true
          cluster-kubernetes:
            kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret # (Optional, default: null). If configured, the plugin uses this file to discover Endpoints. If not configured, it uses the service account mounted to the pod.
            verifySsl:   # Optional, default: true). Whether to verify the Kubernetes API cert or not.
            namespace:   # (Optional, default: null). If configured, the plugin watches Endpoints in this namespace. If null, it watches endpoints in the namespace indicated in the file "/var/run/secrets/kubernetes.io/serviceaccount/namespace".
            httpPortName: # (Optional, default: http). Name of the port configured in the Clouddriver Service that forwards traffic to the Clouddriver HTTP port for REST requests.
            clouddriverServiceNamePrefix: # (Optional, default: spin-clouddriver). Name prefix of the Kubernetes Service pointing to the Clouddriver standard HTTP port.

                                                                  # 2022-10-06 Armory Enterpriseversion 2.28
                                                                  # https://v2-27.docs.armory.io/armory-enterprise/release-notes/rn-armory-agent/agent-plugin/
                                                                  # must be compatible with your Armory Enterprise version
  kustomize:
    clouddriver:
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  initContainers:
                  - name: armory-agent-plugin
                    image: docker.io/armory/kubesvc-plugin:0.11.12 # must be compatible with your Armory Enterprise version
                    volumeMounts:
                      - mountPath: /opt/plugin/target
                        name: armory-agent-plugin-vol
                  containers:
                  - name: clouddriver
                    volumeMounts:
                      - mountPath: /opt/clouddriver/lib/plugins
                        name: armory-agent-plugin-vol
                  volumes:
                  - name: armory-agent-plugin-vol
                    emptyDir: {}