apiVersion: v1
data:
  armory-agent.yaml: |
    clouddriver:
      grpc: spin-clouddriver-grpc.christine-zhao.svc.cluster.local:9091
      insecure: true
      logging:
        level: debug
    logging:
      level: debug
    kubernetes:
      accounts:
      - name: christine-sa
        kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret
        #kubeconfigFile: encryptedFile:vault!e:secret!p:spinnaker/kubernetes!k:config
        # insecure:
        # context:
        # oAuthScopes:
        # serviceAccount: true
        # serviceAccountName: christine-spin-sa
        # namespaces: [spin-agent,christine-agent]
        # omitNamespaces: []
        # onlyNamespacedResources:
        kinds: []
        omitKinds: []
        # customResourceDefinitions: [{kind:}]
        metrics: false
        # permissions: []
        # maxResumableResourceAgeMs:
        # onlySpinnakerManaged:
        # noProxy:
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"armory-agent.yaml":"clouddriver:\n  grpc: spin-clouddriver-grpc:9091\n  insecure: true\nkubernetes:\n  accounts:\n  - name: christine-agent\n    kubeconfigFile: encryptedFile:secrets-manager!r:us-east-2!s:christine-spin-secret\n    #kubeconfigFile: encryptedFile:vault!e:secret!p:spinnaker/kubernetes!k:config\n    # insecure:\n    # context:\n    # oAuthScopes:\n    # serviceAccount: true\n    # serviceAccountName: christine-spin-sa\n    # namespaces: [spin-agent,christine-agent]\n    # omitNamespaces: []\n    # onlyNamespacedResources:\n    kinds: []\n    omitKinds: []\n    # customResourceDefinitions: [{kind:}]\n    metrics: false\n    # permissions: []\n    # maxResumableResourceAgeMs:\n    # onlySpinnakerManaged:\n    # noProxy:\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"armory-agent-config","namespace":"spin-agent"}}
  creationTimestamp: "2022-09-27T12:10:01Z"
  name: armory-agent-config
  namespace: spin-agent
  resourceVersion: "576415592"
  uid: 0a5f7d7c-5d86-4a84-82d2-ebd74c09f3c5
